gui:
  theme:
    selectedLineBgColor:
      - black
    optionsTextColor:
      - cyan
promptToReturnFromSubprocess: false
os:
  open: 'kitty --detach nvim "{{filename}}"'
git:
  diffRenderers:
    - command: 'delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}" --hunk-header-decoration-style=none'
    - command: 'delta --dark --paging=never --line-numbers --side-by-side --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"'
  overrideGpg: true
customCommands:
  - key: 'F'
    command: 'git pull --rebase --autostash origin {{.SelectedLocalBranch.Name}}'
    context: 'localBranches'
    output: log
  - key: 'I'
    context: 'files, commitFiles'
    description: Preview image
    command: 'kitten icat --hold {{.SelectedPath | quote}}'
    output: terminal
