# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
version: 3
console_title_template: "{{if .Root}} ⚡ {{end}}{{.Folder | replace \"~\" \"🏠\"}}\n@ {{.HostName}}"
final_space: false

palette:
  primary: "#1e40af"
  secondary: "#172554"
  text: "#000000"

blocks:
  - type: prompt
    alignment: left
    segments:
      - type: os
        leading_diamond: 
        trailing_diamond: 
        template: " {{ .Icon }} "
        foreground: "#FFFFFF"
        background: p:secondary
        style: diamond
      - type: root
        leading_diamond: "<transparent,#DE2121>\ue0b0</>"
        trailing_diamond: 
        template: " \uf0e7 "
        foreground: "#FFFFFF"
        background: "#DE2121"
        style: diamond
      - type: path
        options:
          folder_icon: ...
          folder_separator_icon: <transparent>  </>
          style: agnoster_short
        template: " {{ .Path }} "
        powerline_symbol: 
        trailing_diamond: 
        foreground: p:text
        background: p:primary
        style: diamond
      - type: git
        options:
          fetch_status: true
          fetch_upstream_icon: true
        template: " {{ .UpstreamIcon }} {{ .HEAD }} {{ .BranchStatus }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} "
        foreground: "#FFFFFF"
        powerline_symbol: 
        leading_powerline_symbol: 
        background: "#15803d"
        style: powerline
        background_templates:
          - "{{ if or (.Working.Changed) (.Staging.Changed) }}#ca8a04{{ end }}"
          - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ca8a04{{ end }}"
          - "{{ if gt .Ahead 0 }}#ca8a04{{ end }}"
          - "{{ if gt .Behind 0 }}#ca8a04{{ end }}"
  - type: rprompt
    segments:
      - type: status
        leading_diamond: <background,transparent></>
        trailing_diamond: <transparent,background></>
        template: " {{ reason .Code }} "
        foreground: "#ffffff"
        background: "#910000"
        style: diamond
      - type: executiontime
        options:
          style: dallas
          always_enabled: true
        leading_diamond: "<p:primary, transparent>\ue0b2</>"
        template: " {{ .FormattedMs }}s "
        foreground: p:secondary
        background: p:primary
        style: diamond
      - type: session
        style: diamond
        foreground: "#ca8a04"
        background: p:primary
        template: "{{ if .SSHSession }} {{ .UserName }}@{{ .HostName }} {{ end }}"
